---
- name: give information for template.j2
  hosts: #[my hosts section in inventory.ini ex dbs ]
  gather_facts: yes
  become: no 
  tasks:
    - name: get uptime of all systems
      shell: uptime
      register: uptime
      
    - name: copy information of what we got in our local
      template:
        src: /root/template.j2
        dest: "/root/report.{{ansible_date_time.iso8601_basic_short}}.txt"
      run_once: yes
      delegate_to: localhost